### ISSUE TITLE
add-on down 

### ISSUE THREAD

**Issue by KillerCroc1** [JCB9090/juan-carlos-torrents-2#11]
are you having api or server issues as you have vanished from addons.strem.io and in the app add-on section

**Comment by solancer** [comment]
![screen shot 2017-04-04 at 2 17 47 am](https://cloud.githubusercontent.com/assets/800668/24631174/03366cb2-18dd-11e7-9a10-a8b966e0dd9c.png)

**Comment by KillerCroc1** [comment]
im getting this 
![screen shot 2017-04-03 at 18 43 11](https://cloud.githubusercontent.com/assets/26205251/24631310/b854c38a-18b7-11e7-8aad-2f85f7786daf.png)
